//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.DataAPIGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImageCollectionItemMappingApi : DataService.DataAPIGen.BaseApi<DataService.Models.Entities.ProductImageCollectionItemMapping, DataService.ViewModels.ProductImageCollectionItemMappingViewModel, DataService.Models.Entities.Services.IProductImageCollectionItemMappingService>
    {
    	
    }
}
