//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.DataAPIGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistoryApi : DataService.DataAPIGen.BaseApi<DataService.Models.Entities.RequestHistory, DataService.ViewModels.RequestHistoryViewModel, DataService.Models.Entities.Services.IRequestHistoryService>
    {
    	
    }
}
