//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.AspNetUser>
    {
    	
    			public virtual string Id { get; set; }
    			public virtual string Email { get; set; }
    			public virtual bool EmailConfirmed { get; set; }
    			public virtual string PasswordHash { get; set; }
    			public virtual string SecurityStamp { get; set; }
    			public virtual string PhoneNumber { get; set; }
    			public virtual bool PhoneNumberConfirmed { get; set; }
    			public virtual bool TwoFactorEnabled { get; set; }
    			public virtual Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    			public virtual bool LockoutEnabled { get; set; }
    			public virtual int AccessFailedCount { get; set; }
    			public virtual string UserName { get; set; }
    			public virtual string FullName { get; set; }
    			public virtual Nullable<int> AdminStoreId { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual Nullable<int> CustomerId { get; set; }
    			public virtual Nullable<int> EmployeeId { get; set; }
    	
    	public AspNetUserViewModel() : base() { }
    	public AspNetUserViewModel(DataService.Models.Entities.AspNetUser entity) : base(entity) { }
    
    }
}
