//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Attendance>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int EmployeeId { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<System.DateTime> CheckMin { get; set; }
    			public virtual Nullable<System.DateTime> CheckMax { get; set; }
    			public virtual Nullable<System.TimeSpan> TotalWorkTime { get; set; }
    			public virtual Nullable<int> Status { get; set; }
    			public virtual System.DateTime ShiftMin { get; set; }
    			public virtual System.DateTime ShiftMax { get; set; }
    			public virtual System.TimeSpan ExpandTime { get; set; }
    			public virtual string UpdatePerson { get; set; }
    			public virtual Nullable<int> ProcessingStatus { get; set; }
    			public virtual string Note { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual int TimeFramId { get; set; }
    			public virtual Nullable<System.TimeSpan> BreakTime { get; set; }
    			public virtual Nullable<System.DateTime> RequestedCheckOut { get; set; }
    			public virtual Nullable<System.DateTime> RequestedCheckIn { get; set; }
    			public virtual Nullable<int> IsRequested { get; set; }
    			public virtual string ApprovePerson { get; set; }
    			public virtual string NoteRequest { get; set; }
    			public virtual Nullable<System.DateTime> LastCheckBeforeShift { get; set; }
    			public virtual Nullable<System.DateTime> FirstCheckAfterShift { get; set; }
    			public virtual Nullable<bool> IsOverTime { get; set; }
    			public virtual Nullable<int> InMode { get; set; }
    			public virtual Nullable<int> OutMode { get; set; }
    			public virtual Nullable<int> BreakCount { get; set; }
    			public virtual Nullable<System.TimeSpan> CheckInExpandTime { get; set; }
    			public virtual Nullable<System.TimeSpan> CheckOutExpandTime { get; set; }
    			public virtual Nullable<System.TimeSpan> ComeLateExpandTime { get; set; }
    			public virtual Nullable<System.TimeSpan> LeaveEarlyExpandTime { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    	
    	public AttendanceViewModel() : base() { }
    	public AttendanceViewModel(DataService.Models.Entities.Attendance entity) : base(entity) { }
    
    }
}
