//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.BlogPost>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Title { get; set; }
    			public virtual string BlogContent { get; set; }
    			public virtual string Excerpt { get; set; }
    			public virtual Nullable<int> BlogCategoryId { get; set; }
    			public virtual string PageTitle { get; set; }
    			public virtual string MetaDescription { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual string Image { get; set; }
    			public virtual string Author { get; set; }
    			public virtual System.DateTime CreatedTime { get; set; }
    			public virtual System.DateTime UpdatedTime { get; set; }
    			public virtual string SeoName { get; set; }
    			public virtual string MetaKeyword { get; set; }
    			public virtual Nullable<int> TotalVisit { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual Nullable<System.DateTime> EndDate { get; set; }
    			public virtual Nullable<System.DateTime> StartDate { get; set; }
    			public virtual string Title_En { get; set; }
    			public virtual string Opening { get; set; }
    			public virtual Nullable<int> Opening_En { get; set; }
    			public virtual string BlogContent_En { get; set; }
    			public virtual string URL { get; set; }
    			public virtual string PageTitle_En { get; set; }
    			public virtual Nullable<int> Position { get; set; }
    			public virtual Nullable<int> Status { get; set; }
    			public virtual string LastUpdatePerson { get; set; }
    			public virtual string Reference { get; set; }
    			public virtual string LinkRef1 { get; set; }
    			public virtual string LinkRef2 { get; set; }
    			public virtual string LinkRef3 { get; set; }
    			public virtual string LinkRef4 { get; set; }
    			public virtual string LinkRef5 { get; set; }
    			public virtual Nullable<int> BlogType { get; set; }
    			public virtual Nullable<int> LocationId { get; set; }
    			public virtual string AuthorRefer { get; set; }
    			public virtual string UserApprove { get; set; }
    			public virtual Nullable<System.DateTime> PublicDate { get; set; }
    			public virtual Nullable<int> BlogPostCollectionNumber { get; set; }
    			public virtual string Name_EN { get; set; }
    			public virtual string Description_EN { get; set; }
    			public virtual string BlogCategoryIds { get; set; }
    			public virtual string TagIds { get; set; }
    	
    	public BlogPostViewModel() : base() { }
    	public BlogPostViewModel(DataService.Models.Entities.BlogPost entity) : base(entity) { }
    
    }
}
