//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostCollectionItemMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.BlogPostCollectionItemMapping>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int BlogPostCollectionId { get; set; }
    			public virtual int BlogPostId { get; set; }
    			public virtual int Position { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public BlogPostCollectionItemMappingViewModel() : base() { }
    	public BlogPostCollectionItemMappingViewModel(DataService.Models.Entities.BlogPostCollectionItemMapping entity) : base(entity) { }
    
    }
}
