//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostImageViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.BlogPostImage>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int BlogPostId { get; set; }
    			public virtual string Title { get; set; }
    			public virtual string ImageUrl { get; set; }
    			public virtual int Position { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual string Type { get; set; }
    			public virtual Nullable<System.DateTime> CreateTime { get; set; }
    			public virtual Nullable<System.DateTime> UpdateTime { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string Link { get; set; }
    			public virtual string SizeType { get; set; }
    			public virtual Nullable<int> Width { get; set; }
    			public virtual Nullable<int> Height { get; set; }
    			public virtual string MimeType { get; set; }
    			public virtual string Slug { get; set; }
    	
    	public BlogPostImageViewModel() : base() { }
    	public BlogPostImageViewModel(DataService.Models.Entities.BlogPostImage entity) : base(entity) { }
    
    }
}
