//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostCollectionViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.BlogPostCollection>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string SeoName { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string SeoDescription { get; set; }
    			public virtual string Link { get; set; }
    			public virtual string PicUrl { get; set; }
    			public virtual Nullable<int> ParentId { get; set; }
    			public virtual string Name_EN { get; set; }
    			public virtual string Description_EN { get; set; }
    			public virtual Nullable<bool> IsDisplay { get; set; }
    			public virtual Nullable<int> Position { get; set; }
    			public virtual string SeoKeyword { get; set; }
    			public virtual Nullable<int> Limitation { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual string SeoName1 { get; set; }
    	
    	public BlogPostCollectionViewModel() : base() { }
    	public BlogPostCollectionViewModel(DataService.Models.Entities.BlogPostCollection entity) : base(entity) { }
    
    }
}
