//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Brand>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string BrandName { get; set; }
    			public virtual System.DateTime CreateDate { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string CompanyName { get; set; }
    			public virtual string ContactPerson { get; set; }
    			public virtual string PhoneNumber { get; set; }
    			public virtual string Fax { get; set; }
    			public virtual string Website { get; set; }
    			public virtual string VATCode { get; set; }
    			public virtual Nullable<int> VATTemplate { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string ApiSMSKey { get; set; }
    			public virtual string SecurityApiSMSKey { get; set; }
    			public virtual Nullable<int> SMSType { get; set; }
    			public virtual string BrandNameSMS { get; set; }
    			public virtual string JsonConfigUrl { get; set; }
    			public virtual string BrandFeatureFilter { get; set; }
    			public virtual Nullable<int> WiskyId { get; set; }
    			public virtual string DefaultDashBoard { get; set; }
    			public virtual string RSAPrivateKey { get; set; }
    			public virtual string RSAPublicKey { get; set; }
    			public virtual string PGPPassword { get; set; }
    			public virtual string PGPPrivateKey { get; set; }
    			public virtual string PGPPulblicKey { get; set; }
    			public virtual string DesKey { get; set; }
    			public virtual string DesVector { get; set; }
    			public virtual string AccessToken { get; set; }
    			public virtual string TaxCode { get; set; }
    	
    	public BrandViewModel() : base() { }
    	public BrandViewModel(DataService.Models.Entities.Brand entity) : base(entity) { }
    
    }
}
