//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryExtraMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.CategoryExtraMapping>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int PrimaryCategoryId { get; set; }
    			public virtual int ExtraCategoryId { get; set; }
    			public virtual bool IsEnable { get; set; }
    	
    	public CategoryExtraMappingViewModel() : base() { }
    	public CategoryExtraMappingViewModel(DataService.Models.Entities.CategoryExtraMapping entity) : base(entity) { }
    
    }
}
