//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Contact>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual Nullable<bool> Gender { get; set; }
    			public virtual string Email { get; set; }
    			public virtual string ProfileUrl { get; set; }
    			public virtual Nullable<System.DateTime> Birthday { get; set; }
    			public virtual string ImageUrl { get; set; }
    			public virtual string Phone { get; set; }
    			public virtual Nullable<System.DateTime> CreateDate { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual string Username { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string Organization { get; set; }
    			public virtual string Job { get; set; }
    			public virtual string Position { get; set; }
    			public virtual Nullable<int> FirstLocationId { get; set; }
    			public virtual string Fax { get; set; }
    			public virtual Nullable<int> TotalVisted { get; set; }
    			public virtual Nullable<int> TypeContactFrom { get; set; }
    			public virtual Nullable<System.DateTime> LastVisted { get; set; }
    	
    	public ContactViewModel() : base() { }
    	public ContactViewModel(DataService.Models.Entities.Contact entity) : base(entity) { }
    
    }
}
