//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCategoryViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.CostCategory>
    {
    	
    			public virtual int CatID { get; set; }
    			public virtual string CatName { get; set; }
    			public virtual Nullable<int> Type { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    	
    	public CostCategoryViewModel() : base() { }
    	public CostCategoryViewModel(DataService.Models.Entities.CostCategory entity) : base(entity) { }
    
    }
}
