//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerStoreReportMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.CustomerStoreReportMapping>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int CustomerID { get; set; }
    			public virtual int StoreID { get; set; }
    			public virtual Nullable<int> TotalOrder { get; set; }
    			public virtual Nullable<double> TotalAmount { get; set; }
    			public virtual Nullable<double> AverageAmount { get; set; }
    			public virtual Nullable<int> VisitAmount { get; set; }
    			public virtual Nullable<int> DateAmount { get; set; }
    			public virtual Nullable<double> Frequency { get; set; }
    			public virtual System.DateTime LastVisitDate { get; set; }
    			public virtual System.DateTime UpdateDate { get; set; }
    	
    	public CustomerStoreReportMappingViewModel() : base() { }
    	public CustomerStoreReportMappingViewModel(DataService.Models.Entities.CustomerStoreReportMapping entity) : base(entity) { }
    
    }
}
