//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFilterViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.CustomerFilter>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Description { get; set; }
    			public virtual Nullable<int> StoreID { get; set; }
    			public virtual Nullable<int> CusTypeID { get; set; }
    			public virtual Nullable<int> AgeFrom { get; set; }
    			public virtual Nullable<int> AgeTo { get; set; }
    			public virtual Nullable<int> BirthdayMonth { get; set; }
    			public virtual Nullable<System.DateTime> BirthdayFrom { get; set; }
    			public virtual Nullable<System.DateTime> BirthdayTo { get; set; }
    			public virtual Nullable<int> BirthdayOption { get; set; }
    			public virtual Nullable<bool> Gender { get; set; }
    			public virtual Nullable<int> VisitedTimesFrom { get; set; }
    			public virtual Nullable<int> VisitedTimesTo { get; set; }
    			public virtual Nullable<bool> IsEnableCusType { get; set; }
    			public virtual Nullable<bool> IsEnableAge { get; set; }
    			public virtual Nullable<bool> IsEnableBirthday { get; set; }
    			public virtual Nullable<bool> IsEnableGender { get; set; }
    			public virtual Nullable<bool> IsEnableVisitedTimes { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    	
    	public CustomerFilterViewModel() : base() { }
    	public CustomerFilterViewModel(DataService.Models.Entities.CustomerFilter entity) : base(entity) { }
    
    }
}
