//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTypeViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.CustomerType>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string CustomerType1 { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    	
    	public CustomerTypeViewModel() : base() { }
    	public CustomerTypeViewModel(DataService.Models.Entities.CustomerType entity) : base(entity) { }
    
    }
}
