//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProductMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.CustomerProductMapping>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int CustomerID { get; set; }
    			public virtual int ProductID { get; set; }
    			public virtual int TotalQuantity { get; set; }
    			public virtual System.DateTime UpdateDate { get; set; }
    	
    	public CustomerProductMappingViewModel() : base() { }
    	public CustomerProductMappingViewModel(DataService.Models.Entities.CustomerProductMapping entity) : base(entity) { }
    
    }
}
