//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateProductViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.DateProduct>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual System.DateTime Date { get; set; }
    			public virtual int ProductId { get; set; }
    			public virtual int StoreID { get; set; }
    			public virtual int Quantity { get; set; }
    			public virtual double TotalAmount { get; set; }
    			public virtual double Discount { get; set; }
    			public virtual double FinalAmount { get; set; }
    			public virtual Nullable<int> CategoryId_ { get; set; }
    			public virtual string ProductName_ { get; set; }
    			public virtual Nullable<int> Time0Quantity { get; set; }
    			public virtual Nullable<int> Time1Quantity { get; set; }
    			public virtual Nullable<int> Time2Quantity { get; set; }
    			public virtual Nullable<int> Time3Quantity { get; set; }
    			public virtual Nullable<int> Time4Quantity { get; set; }
    			public virtual Nullable<int> Time5Quantity { get; set; }
    			public virtual Nullable<int> Time6Quantity { get; set; }
    			public virtual Nullable<int> Time7Quantity { get; set; }
    			public virtual Nullable<int> Time8Quantity { get; set; }
    			public virtual Nullable<int> Time9Quantity { get; set; }
    			public virtual Nullable<int> Time10Quantity { get; set; }
    			public virtual Nullable<int> Time11Quantity { get; set; }
    			public virtual Nullable<int> Time12Quantity { get; set; }
    			public virtual Nullable<int> Time13Quantity { get; set; }
    			public virtual Nullable<int> Time14Quantity { get; set; }
    			public virtual Nullable<int> Time15Quantity { get; set; }
    			public virtual Nullable<int> Time16Quantity { get; set; }
    			public virtual Nullable<int> Time17Quantity { get; set; }
    			public virtual Nullable<int> Time18Quantity { get; set; }
    			public virtual Nullable<int> Time19Quantity { get; set; }
    			public virtual Nullable<int> Time20Quantity { get; set; }
    			public virtual Nullable<int> Time21Quantity { get; set; }
    			public virtual Nullable<int> Time22Quantity { get; set; }
    			public virtual Nullable<int> Time23Quantity { get; set; }
    			public virtual Nullable<int> OrderQuantity { get; set; }
    			public virtual Nullable<int> QuantityAtStore { get; set; }
    			public virtual Nullable<int> QuantityTakeAway { get; set; }
    			public virtual Nullable<int> QuantityDelivery { get; set; }
    	
    	public DateProductViewModel() : base() { }
    	public DateProductViewModel(DataService.Models.Entities.DateProduct entity) : base(entity) { }
    
    }
}
