//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateReportViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.DateReport>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual System.DateTime Date { get; set; }
    			public virtual string CreateBy { get; set; }
    			public virtual int Status { get; set; }
    			public virtual int StoreID { get; set; }
    			public virtual Nullable<double> TotalAmount { get; set; }
    			public virtual Nullable<double> FinalAmount { get; set; }
    			public virtual Nullable<double> Discount { get; set; }
    			public virtual Nullable<double> DiscountOrderDetail { get; set; }
    			public virtual Nullable<double> TotalCash { get; set; }
    			public virtual int TotalOrder { get; set; }
    			public virtual int TotalOrderAtStore { get; set; }
    			public virtual int TotalOrderTakeAway { get; set; }
    			public virtual int TotalOrderDelivery { get; set; }
    			public virtual double TotalOrderDetail { get; set; }
    			public virtual double TotalOrderFeeItem { get; set; }
    			public virtual int TotalOrderCard { get; set; }
    			public virtual Nullable<int> TotalOrderCanceled { get; set; }
    			public virtual Nullable<int> TotalOrderPreCanceled { get; set; }
    			public virtual Nullable<double> FinalAmountAtStore { get; set; }
    			public virtual Nullable<double> FinalAmountTakeAway { get; set; }
    			public virtual Nullable<double> FinalAmountDelivery { get; set; }
    			public virtual Nullable<double> FinalAmountCard { get; set; }
    			public virtual Nullable<double> FinalAmountCanceled { get; set; }
    			public virtual Nullable<double> FinalAmountPreCanceled { get; set; }
    	
    	public DateReportViewModel() : base() { }
    	public DateReportViewModel(DataService.Models.Entities.DateReport entity) : base(entity) { }
    
    }
}
