//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateHotelReportViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.DateHotelReport>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual System.DateTime Date { get; set; }
    			public virtual string CreateBy { get; set; }
    			public virtual int Status { get; set; }
    			public virtual int StoreID { get; set; }
    			public virtual double TotalAmount { get; set; }
    			public virtual double Discount { get; set; }
    			public virtual double FinalAmount { get; set; }
    			public virtual double TotalOrderDetail { get; set; }
    			public virtual double TotalOrderFeeItem { get; set; }
    	
    	public DateHotelReportViewModel() : base() { }
    	public DateHotelReportViewModel(DataService.Models.Entities.DateHotelReport entity) : base(entity) { }
    
    }
}
