//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Device>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string DeviceName { get; set; }
    			public virtual string DeviceCode { get; set; }
    			public virtual string Config { get; set; }
    			public virtual Nullable<bool> Status { get; set; }
    			public virtual Nullable<int> StoreId { get; set; }
    	
    	public DeviceViewModel() : base() { }
    	public DeviceViewModel(DataService.Models.Entities.Device entity) : base(entity) { }
    
    }
}
