//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.District>
    {
    	
    			public virtual int DistrictCode { get; set; }
    			public virtual string DistrictName { get; set; }
    			public virtual string DistrictType { get; set; }
    			public virtual int ProvinceCode { get; set; }
    			public virtual Nullable<decimal> PriceDelivery { get; set; }
    			public virtual Nullable<int> AreaDistrictId { get; set; }
    	
    	public DistrictViewModel() : base() { }
    	public DistrictViewModel(DataService.Models.Entities.District entity) : base(entity) { }
    
    }
}
