//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFingerViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.EmployeeFinger>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<int> EmpId { get; set; }
    			public virtual string EmpEnrollNumber { get; set; }
    			public virtual int FingerIndex { get; set; }
    			public virtual string FingerData { get; set; }
    			public virtual Nullable<int> Type { get; set; }
    			public virtual string NameEmployeeInMachine { get; set; }
    	
    	public EmployeeFingerViewModel() : base() { }
    	public EmployeeFingerViewModel(DataService.Models.Entities.EmployeeFinger entity) : base(entity) { }
    
    }
}
