//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInStoreViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.EmployeeInStore>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int EmployeeId { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual System.DateTime AssignedDate { get; set; }
    			public virtual Nullable<int> Status { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public EmployeeInStoreViewModel() : base() { }
    	public EmployeeInStoreViewModel(DataService.Models.Entities.EmployeeInStore entity) : base(entity) { }
    
    }
}
