//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoritedViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Favorited>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string UserID { get; set; }
    			public virtual int ProductID { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<bool> FavoriteStt { get; set; }
    	
    	public FavoritedViewModel() : base() { }
    	public FavoritedViewModel(DataService.Models.Entities.Favorited entity) : base(entity) { }
    
    }
}
