//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FingerScanMachineViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.FingerScanMachine>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string MachineCode { get; set; }
    			public virtual string Name { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual string Url { get; set; }
    			public virtual string Ip { get; set; }
    			public virtual string BrandOfMachine { get; set; }
    			public virtual Nullable<System.DateTime> DateOfManufacture { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public FingerScanMachineViewModel() : base() { }
    	public FingerScanMachineViewModel(DataService.Models.Entities.FingerScanMachine entity) : base(entity) { }
    
    }
}
