//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Group>
    {
    	
    			public virtual int GroupId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Description { get; set; }
    			public virtual Nullable<bool> IsDisplayed { get; set; }
    			public virtual int BrandId { get; set; }
    	
    	public GroupViewModel() : base() { }
    	public GroupViewModel(DataService.Models.Entities.Group entity) : base(entity) { }
    
    }
}
