//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageCollectionViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ImageCollection>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public ImageCollectionViewModel() : base() { }
    	public ImageCollectionViewModel(DataService.Models.Entities.ImageCollection entity) : base(entity) { }
    
    }
}
