//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCheckingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.InventoryChecking>
    {
    	
    			public virtual int CheckingId { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual System.DateTime CheckingDate { get; set; }
    			public virtual string Creator { get; set; }
    			public virtual int Status { get; set; }
    	
    	public InventoryCheckingViewModel() : base() { }
    	public InventoryCheckingViewModel(DataService.Models.Entities.InventoryChecking entity) : base(entity) { }
    
    }
}
