//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDateReportItemViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.InventoryDateReportItem>
    {
    	
    			public virtual int ItemID { get; set; }
    			public virtual double Quantity { get; set; }
    			public virtual int ReportID { get; set; }
    			public virtual Nullable<double> ImportAmount { get; set; }
    			public virtual Nullable<double> ExportAmount { get; set; }
    			public virtual Nullable<double> CancelAmount { get; set; }
    			public virtual Nullable<double> SoldAmount { get; set; }
    			public virtual Nullable<double> ReturnAmount { get; set; }
    			public virtual Nullable<double> ChangeInventoryAmount { get; set; }
    			public virtual Nullable<double> TheoryAmount { get; set; }
    			public virtual Nullable<double> RealAmount { get; set; }
    			public virtual Nullable<double> TotalExport { get; set; }
    			public virtual Nullable<double> TotalImport { get; set; }
    			public virtual Nullable<double> ReceivedChangeInventoryAmount { get; set; }
    			public virtual Nullable<bool> IsSelected { get; set; }
    			public virtual double Price { get; set; }
    	
    	public InventoryDateReportItemViewModel() : base() { }
    	public InventoryDateReportItemViewModel(DataService.Models.Entities.InventoryDateReportItem entity) : base(entity) { }
    
    }
}
