//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCheckingItemViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.InventoryCheckingItem>
    {
    	
    			public virtual int InventoryCheckingID { get; set; }
    			public virtual int ItemID { get; set; }
    			public virtual int CheckingId { get; set; }
    			public virtual double Quantity { get; set; }
    			public virtual string Unit { get; set; }
    			public virtual Nullable<double> Price { get; set; }
    	
    	public InventoryCheckingItemViewModel() : base() { }
    	public InventoryCheckingItemViewModel(DataService.Models.Entities.InventoryCheckingItem entity) : base(entity) { }
    
    }
}
