//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReceiptItemViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.InventoryReceiptItem>
    {
    	
    			public virtual int ReceiptID { get; set; }
    			public virtual int ItemID { get; set; }
    			public virtual double Quantity { get; set; }
    			public virtual double Price { get; set; }
    			public virtual Nullable<System.DateTime> DateExpired { get; set; }
    			public virtual Nullable<bool> IsUnit1 { get; set; }
    	
    	public InventoryReceiptItemViewModel() : base() { }
    	public InventoryReceiptItemViewModel(DataService.Models.Entities.InventoryReceiptItem entity) : base(entity) { }
    
    }
}
