//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTemplateReportViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.InventoryTemplateReport>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Description { get; set; }
    			public virtual int BrandId { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public InventoryTemplateReportViewModel() : base() { }
    	public InventoryTemplateReportViewModel(DataService.Models.Entities.InventoryTemplateReport entity) : base(entity) { }
    
    }
}
