//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipTypeViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.MembershipType>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string TypeName { get; set; }
    			public virtual string AppendCode { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    			public virtual Nullable<int> TypeLevel { get; set; }
    			public virtual Nullable<int> TypePoint { get; set; }
    			public virtual int BrandId { get; set; }
    			public virtual Nullable<bool> IsMobile { get; set; }
    	
    	public MembershipTypeViewModel() : base() { }
    	public MembershipTypeViewModel(DataService.Models.Entities.MembershipType entity) : base(entity) { }
    
    }
}
