//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Menu>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string MenuText { get; set; }
    			public virtual string Area { get; set; }
    			public virtual string Controller { get; set; }
    			public virtual string Action { get; set; }
    			public virtual string IconCss { get; set; }
    			public virtual int DisplayOrder { get; set; }
    			public virtual Nullable<int> ParentMenuId { get; set; }
    			public virtual int MenuLevel { get; set; }
    			public virtual bool Status { get; set; }
    			public virtual int MenuTypeCode { get; set; }
    			public virtual Nullable<int> FeatureCode { get; set; }
    			public virtual Nullable<int> MenuState { get; set; }
    			public virtual Nullable<int> MenuUrlCode { get; set; }
    	
    	public MenuViewModel() : base() { }
    	public MenuViewModel(DataService.Models.Entities.Menu entity) : base(entity) { }
    
    }
}
