//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Notification>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Title { get; set; }
    			public virtual string Title_En { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string Description_En { get; set; }
    			public virtual Nullable<int> Type { get; set; }
    			public virtual Nullable<System.DateTime> CreateDate { get; set; }
    			public virtual Nullable<System.DateTime> UpdateDate { get; set; }
    			public virtual string PicUrl { get; set; }
    			public virtual string Opening { get; set; }
    			public virtual string Content { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    			public virtual Nullable<int> CustomerId { get; set; }
    	
    	public NotificationViewModel() : base() { }
    	public NotificationViewModel(DataService.Models.Entities.Notification entity) : base(entity) { }
    
    }
}
