//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.OrderDetail>
    {
    	
    			public virtual int OrderDetailID { get; set; }
    			public virtual int RentID { get; set; }
    			public virtual int ProductID { get; set; }
    			public virtual double TotalAmount { get; set; }
    			public virtual int Quantity { get; set; }
    			public virtual System.DateTime OrderDate { get; set; }
    			public virtual int Status { get; set; }
    			public virtual double FinalAmount { get; set; }
    			public virtual bool IsAddition { get; set; }
    			public virtual string DetailDescription { get; set; }
    			public virtual double Discount { get; set; }
    			public virtual Nullable<double> TaxPercent { get; set; }
    			public virtual Nullable<double> TaxValue { get; set; }
    			public virtual double UnitPrice { get; set; }
    			public virtual Nullable<int> ProductType { get; set; }
    			public virtual Nullable<int> ParentId { get; set; }
    			public virtual Nullable<int> StoreId { get; set; }
    			public virtual Nullable<int> ProductOrderType { get; set; }
    			public virtual int ItemQuantity { get; set; }
    			public virtual Nullable<int> TmpDetailId { get; set; }
    			public virtual Nullable<int> OrderDetailPromotionMappingId { get; set; }
    			public virtual Nullable<int> OrderPromotionMappingId { get; set; }
    			public virtual string OrderDetailAtt1 { get; set; }
    			public virtual string OrderDetailAtt2 { get; set; }
    	
    	public OrderDetailViewModel() : base() { }
    	public OrderDetailViewModel(DataService.Models.Entities.OrderDetail entity) : base(entity) { }
    
    }
}
