//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.PartnerMapping>
    {
    	
    			public virtual int BrandId { get; set; }
    			public virtual int PartnerId { get; set; }
    			public virtual string Config { get; set; }
    			public virtual Nullable<bool> Status { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    			public virtual int Id { get; set; }
    	
    	public PartnerMappingViewModel() : base() { }
    	public PartnerMappingViewModel(DataService.Models.Entities.PartnerMapping entity) : base(entity) { }
    
    }
}
