//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Partner>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string PartnerCode { get; set; }
    			public virtual string PartnerName { get; set; }
    			public virtual Nullable<int> PartnerType { get; set; }
    			public virtual string AvatarURL { get; set; }
    			public virtual string Phone { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string SchemaConfig { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    			public virtual string PartnerAddress { get; set; }
    	
    	public PartnerViewModel() : base() { }
    	public PartnerViewModel(DataService.Models.Entities.Partner entity) : base(entity) { }
    
    }
}
