//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReportViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.PaymentReport>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string CreateBy { get; set; }
    			public virtual int Status { get; set; }
    			public virtual System.DateTime Date { get; set; }
    			public virtual int StoreID { get; set; }
    			public virtual double CashAmount { get; set; }
    			public virtual double MemberCardAmount { get; set; }
    			public virtual double BankAmount { get; set; }
    			public virtual double VoucherAmount { get; set; }
    			public virtual double DebtAmount { get; set; }
    			public virtual double OtherAmount { get; set; }
    			public virtual double PayDebtAmount { get; set; }
    			public virtual double ReceiptAmount { get; set; }
    			public virtual double SpendAmount { get; set; }
    	
    	public PaymentReportViewModel() : base() { }
    	public PaymentReportViewModel(DataService.Models.Entities.PaymentReport entity) : base(entity) { }
    
    }
}
