//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Payment>
    {
    	
    			public virtual int PaymentID { get; set; }
    			public virtual Nullable<int> ToRentID { get; set; }
    			public virtual double Amount { get; set; }
    			public virtual string CurrencyCode { get; set; }
    			public virtual decimal FCAmount { get; set; }
    			public virtual string Notes { get; set; }
    			public virtual System.DateTime PayTime { get; set; }
    			public virtual int Status { get; set; }
    			public virtual int Type { get; set; }
    			public virtual Nullable<double> RealAmount { get; set; }
    			public virtual string CardCode { get; set; }
    			public virtual Nullable<int> CostID { get; set; }
    			public virtual Nullable<int> AccountID { get; set; }
    			public virtual Nullable<int> CardId { get; set; }
    	
    	public PaymentViewModel() : base() { }
    	public PaymentViewModel(DataService.Models.Entities.Payment entity) : base(entity) { }
    
    }
}
