//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollPeriodViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.PayrollPeriod>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<int> PaySlipTemplateId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual Nullable<System.DateTime> FromDate { get; set; }
    			public virtual Nullable<System.DateTime> ToDate { get; set; }
    			public virtual Nullable<bool> IsActive { get; set; }
    	
    	public PayrollPeriodViewModel() : base() { }
    	public PayrollPeriodViewModel(DataService.Models.Entities.PayrollPeriod entity) : base(entity) { }
    
    }
}
