//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayslipAttributeMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.PayslipAttributeMapping>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<int> PayslipId { get; set; }
    			public virtual Nullable<int> AttributeId { get; set; }
    			public virtual Nullable<int> Value { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public PayslipAttributeMappingViewModel() : base() { }
    	public PayslipAttributeMappingViewModel(DataService.Models.Entities.PayslipAttributeMapping entity) : base(entity) { }
    
    }
}
