//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosFileViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.PosFile>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string FileName { get; set; }
    			public virtual Nullable<int> StoreId { get; set; }
    			public virtual int BrandId { get; set; }
    			public virtual string Version { get; set; }
    	
    	public PosFileViewModel() : base() { }
    	public PosFileViewModel(DataService.Models.Entities.PosFile entity) : base(entity) { }
    
    }
}
