//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceGroupViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.PriceGroup>
    {
    	
    			public virtual int PriceGroupID { get; set; }
    			public virtual string PriceGroupName { get; set; }
    			public virtual System.DateTime StartDayTime { get; set; }
    			public virtual System.DateTime EndNightTime { get; set; }
    			public virtual double DayPrice { get; set; }
    			public virtual int RoundMinute { get; set; }
    			public virtual double FirstHourPrice { get; set; }
    			public virtual double SecondHourPrice { get; set; }
    			public virtual double ThirdHourPrice { get; set; }
    			public virtual double NextHourPrice { get; set; }
    			public virtual int NightAdditionPriceID { get; set; }
    			public virtual bool IsAvailable { get; set; }
    			public virtual double AdditionPrice { get; set; }
    			public virtual int DayLimitTime1 { get; set; }
    			public virtual double DayPriceLimitTime1 { get; set; }
    			public virtual int DayLimitTime2 { get; set; }
    			public virtual double DayPriceLimitTime2 { get; set; }
    	
    	public PriceGroupViewModel() : base() { }
    	public PriceGroupViewModel(DataService.Models.Entities.PriceGroup entity) : base(entity) { }
    
    }
}
