//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceNightViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.PriceNight>
    {
    	
    			public virtual int RoomPriceID { get; set; }
    			public virtual int PriceGroupID { get; set; }
    			public virtual System.DateTime StartTime { get; set; }
    			public virtual System.DateTime EndTime { get; set; }
    			public virtual double Price { get; set; }
    			public virtual int MaxDuration { get; set; }
    			public virtual double PricePerHour { get; set; }
    			public virtual System.DateTime CheckTime { get; set; }
    	
    	public PriceNightViewModel() : base() { }
    	public PriceNightViewModel(DataService.Models.Entities.PriceNight entity) : base(entity) { }
    
    }
}
