//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItemCategoryViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ProductItemCategory>
    {
    	
    			public virtual int CateID { get; set; }
    			public virtual string CateName { get; set; }
    			public virtual int Type { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public ProductItemCategoryViewModel() : base() { }
    	public ProductItemCategoryViewModel(DataService.Models.Entities.ProductItemCategory entity) : base(entity) { }
    
    }
}
