//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ProductCategory>
    {
    	
    			public virtual int CateID { get; set; }
    			public virtual string CateName { get; set; }
    			public virtual string CateNameEng { get; set; }
    			public virtual int Type { get; set; }
    			public virtual bool IsDisplayed { get; set; }
    			public virtual bool IsDisplayedWebsite { get; set; }
    			public virtual bool IsExtra { get; set; }
    			public virtual int DisplayOrder { get; set; }
    			public virtual string AdjustmentNote { get; set; }
    			public virtual Nullable<int> StoreId { get; set; }
    			public virtual string SeoName { get; set; }
    			public virtual string SeoKeyword { get; set; }
    			public virtual string SeoDescription { get; set; }
    			public virtual string ImageFontAwsomeCss { get; set; }
    			public virtual Nullable<int> ParentCateId { get; set; }
    			public virtual Nullable<int> Position { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual string PicUrl { get; set; }
    			public virtual string BannerUrl { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string DescriptionEng { get; set; }
    			public virtual string BannerDescription { get; set; }
    			public virtual string BannerDescriptionEng { get; set; }
    			public virtual string Att1 { get; set; }
    			public virtual string Att2 { get; set; }
    			public virtual string Att3 { get; set; }
    			public virtual string Att4 { get; set; }
    			public virtual string Att5 { get; set; }
    			public virtual string Att6 { get; set; }
    			public virtual string Att7 { get; set; }
    			public virtual string Att8 { get; set; }
    			public virtual string Att9 { get; set; }
    			public virtual string Att10 { get; set; }
    			public virtual Nullable<double> VAT { get; set; }
    	
    	public ProductCategoryViewModel() : base() { }
    	public ProductCategoryViewModel(DataService.Models.Entities.ProductCategory entity) : base(entity) { }
    
    }
}
