//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBrandViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ProductBrand>
    {
    	
    			public virtual int ProductBrandId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Slug { get; set; }
    			public virtual string Description { get; set; }
    			public virtual Nullable<int> Count { get; set; }
    	
    	public ProductBrandViewModel() : base() { }
    	public ProductBrandViewModel(DataService.Models.Entities.ProductBrand entity) : base(entity) { }
    
    }
}
