//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImageViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ProductImage>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int ProductId { get; set; }
    			public virtual string ImageUrl { get; set; }
    			public virtual string Title { get; set; }
    			public virtual string Description { get; set; }
    			public virtual int Position { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<System.DateTime> CreatedDate { get; set; }
    			public virtual Nullable<System.DateTime> UpdatedDate { get; set; }
    	
    	public ProductImageViewModel() : base() { }
    	public ProductImageViewModel(DataService.Models.Entities.ProductImage entity) : base(entity) { }
    
    }
}
