//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionPartnerViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.PromotionPartner>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string PartnerName { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string CompanyName { get; set; }
    			public virtual string ContactPerson { get; set; }
    			public virtual string PhoneNumber { get; set; }
    			public virtual string Fax { get; set; }
    			public virtual string Website { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string OrderPrefix { get; set; }
    			public virtual string Token { get; set; }
    			public virtual decimal CommissionRate { get; set; }
    			public virtual int CustomerID { get; set; }
    	
    	public PromotionPartnerViewModel() : base() { }
    	public PromotionPartnerViewModel(DataService.Models.Entities.PromotionPartner entity) : base(entity) { }
    
    }
}
