//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Promotion>
    {
    	
    			public virtual int PromotionID { get; set; }
    			public virtual string PromotionCode { get; set; }
    			public virtual string PromotionName { get; set; }
    			public virtual string PromotionClassName { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string ImageCss { get; set; }
    			public virtual int ApplyLevel { get; set; }
    			public virtual int GiftType { get; set; }
    			public virtual bool IsForMember { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual System.DateTime FromDate { get; set; }
    			public virtual System.DateTime ToDate { get; set; }
    			public virtual Nullable<int> ApplyFromTime { get; set; }
    			public virtual Nullable<int> ApplyToTime { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual string ImageUrl { get; set; }
    			public virtual Nullable<bool> IsVoucher { get; set; }
    			public virtual Nullable<bool> IsApplyOnce { get; set; }
    			public virtual Nullable<int> VoucherQuantity { get; set; }
    			public virtual Nullable<int> VoucherUsedQuantity { get; set; }
    			public virtual int PromotionType { get; set; }
    			public virtual Nullable<int> FromHappyDay { get; set; }
    			public virtual Nullable<int> ToHappyDay { get; set; }
    			public virtual Nullable<int> FromHoursHappy { get; set; }
    			public virtual Nullable<int> ToHoursHappy { get; set; }
    			public virtual Nullable<bool> UsingPoint { get; set; }
    			public virtual Nullable<int> ApplyToPartner { get; set; }
    			public virtual Nullable<int> PartnerID { get; set; }
    	
    	public PromotionViewModel() : base() { }
    	public PromotionViewModel(DataService.Models.Entities.Promotion entity) : base(entity) { }
    
    }
}
