//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvinceViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Province>
    {
    	
    			public virtual int ProvinceCode { get; set; }
    			public virtual string ProvinceName { get; set; }
    			public virtual string ProvinceType { get; set; }
    			public virtual Nullable<decimal> BasePriceDelivery { get; set; }
    			public virtual Nullable<int> AreaProvinceId { get; set; }
    	
    	public ProvinceViewModel() : base() { }
    	public ProvinceViewModel(DataService.Models.Entities.Province entity) : base(entity) { }
    
    }
}
