//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Provider>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string ProviderName { get; set; }
    			public virtual Nullable<bool> IsAvailable { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string Phone { get; set; }
    			public virtual string Email { get; set; }
    			public virtual string ManagerName { get; set; }
    			public virtual string License { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual Nullable<int> Type { get; set; }
    			public virtual string VATCode { get; set; }
    			public virtual string AccountNo { get; set; }
    	
    	public ProviderViewModel() : base() { }
    	public ProviderViewModel(DataService.Models.Entities.Provider entity) : base(entity) { }
    
    }
}
