//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingStarViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.RatingStar>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int ProductID { get; set; }
    			public virtual string UserID { get; set; }
    			public virtual Nullable<int> Rate { get; set; }
    	
    	public RatingStarViewModel() : base() { }
    	public RatingStarViewModel(DataService.Models.Entities.RatingStar entity) : base(entity) { }
    
    }
}
