//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTrackingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ReportTracking>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual Nullable<System.DateTime> Date { get; set; }
    			public virtual Nullable<System.DateTime> DateUpdate { get; set; }
    			public virtual string UpdatePerson { get; set; }
    			public virtual Nullable<bool> IsUpdate { get; set; }
    	
    	public ReportTrackingViewModel() : base() { }
    	public ReportTrackingViewModel(DataService.Models.Entities.ReportTracking entity) : base(entity) { }
    
    }
}
