//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistoryViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.RequestHistory>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual int BrandId { get; set; }
    			public virtual Nullable<int> CustomerId { get; set; }
    			public virtual Nullable<System.DateTime> RequestTime { get; set; }
    			public virtual string RequestData { get; set; }
    			public virtual string RequestToken { get; set; }
    			public virtual string RequestType { get; set; }
    			public virtual string RequestUri { get; set; }
    			public virtual string ControllerName { get; set; }
    			public virtual Nullable<int> StatusCode { get; set; }
    			public virtual Nullable<bool> Success { get; set; }
    			public virtual string Message { get; set; }
    			public virtual string ResponseData { get; set; }
    	
    	public RequestHistoryViewModel() : base() { }
    	public RequestHistoryViewModel(DataService.Models.Entities.RequestHistory entity) : base(entity) { }
    
    }
}
