//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Role>
    {
    	
    			public virtual System.Guid ApplicationId { get; set; }
    			public virtual System.Guid RoleId { get; set; }
    			public virtual string RoleName { get; set; }
    			public virtual string Description { get; set; }
    	
    	public RoleViewModel() : base() { }
    	public RoleViewModel(DataService.Models.Entities.Role entity) : base(entity) { }
    
    }
}
