//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomCategoryPriceGroupMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.RoomCategoryPriceGroupMapping>
    {
    	
    			public virtual int CategoryID { get; set; }
    			public virtual int PriceGroupID { get; set; }
    			public virtual bool IsDefault { get; set; }
    	
    	public RoomCategoryPriceGroupMappingViewModel() : base() { }
    	public RoomCategoryPriceGroupMappingViewModel(DataService.Models.Entities.RoomCategoryPriceGroupMapping entity) : base(entity) { }
    
    }
}
