//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Room>
    {
    	
    			public virtual int RoomID { get; set; }
    			public virtual string RoomName { get; set; }
    			public virtual string RoomDescription { get; set; }
    			public virtual int RoomStatus { get; set; }
    			public virtual int FloorID { get; set; }
    			public virtual int CategoryID { get; set; }
    			public virtual bool IsDeleted { get; set; }
    			public virtual Nullable<int> StoreID { get; set; }
    			public virtual Nullable<int> CurrentRentId { get; set; }
    			public virtual Nullable<int> RentStatus { get; set; }
    			public virtual int PosX { get; set; }
    			public virtual int PosSpanX { get; set; }
    			public virtual int PosY { get; set; }
    			public virtual int PosSpanY { get; set; }
    			public virtual Nullable<int> RentType { get; set; }
    	
    	public RoomViewModel() : base() { }
    	public RoomViewModel(DataService.Models.Entities.Room entity) : base(entity) { }
    
    }
}
