//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryHourViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.SalaryHour>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual System.DateTime Date { get; set; }
    			public virtual Nullable<double> Duration { get; set; }
    			public virtual int InsertMode { get; set; }
    			public virtual Nullable<int> EmployeeId { get; set; }
    			public virtual string UpdatePerson { get; set; }
    			public virtual Nullable<int> TimeModeRuleId { get; set; }
    			public virtual string ExistCode { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public SalaryHourViewModel() : base() { }
    	public SalaryHourViewModel(DataService.Models.Entities.SalaryHour entity) : base(entity) { }
    
    }
}
