//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWebViewCounterViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.StoreWebViewCounter>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual int WeeklyViewCount { get; set; }
    			public virtual int MonthlyViewCount { get; set; }
    			public virtual int TotalViewCount { get; set; }
    			public virtual System.DateTime LastUpdate { get; set; }
    			public virtual int TodayViewCount { get; set; }
    			public virtual int YearlyViewCount { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public StoreWebViewCounterViewModel() : base() { }
    	public StoreWebViewCounterViewModel(DataService.Models.Entities.StoreWebViewCounter entity) : base(entity) { }
    
    }
}
