//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreGroupViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.StoreGroup>
    {
    	
    			public virtual int GroupID { get; set; }
    			public virtual string GroupName { get; set; }
    			public virtual string Description { get; set; }
    			public virtual int BrandId { get; set; }
    	
    	public StoreGroupViewModel() : base() { }
    	public StoreGroupViewModel(DataService.Models.Entities.StoreGroup entity) : base(entity) { }
    
    }
}
