//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWebRouteModelViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.StoreWebRouteModel>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int StoreWebRouteId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual int ViewModelType { get; set; }
    			public virtual string IdRouteValueName { get; set; }
    			public virtual string IdRouteDefaultValue { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public StoreWebRouteModelViewModel() : base() { }
    	public StoreWebRouteModelViewModel(DataService.Models.Entities.StoreWebRouteModel entity) : base(entity) { }
    
    }
}
