//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemPartnerMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.SystemPartnerMapping>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int PartnerID { get; set; }
    			public virtual int StoreID { get; set; }
    			public virtual int BrandID { get; set; }
    			public virtual string Att1 { get; set; }
    			public virtual string Att2 { get; set; }
    			public virtual string Att3 { get; set; }
    			public virtual string Att4 { get; set; }
    	
    	public SystemPartnerMappingViewModel() : base() { }
    	public SystemPartnerMappingViewModel(DataService.Models.Entities.SystemPartnerMapping entity) : base(entity) { }
    
    }
}
