//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.TagMapping>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int TagId { get; set; }
    			public virtual int CategoryId { get; set; }
    			public virtual int TagBlogId { get; set; }
    	
    	public TagMappingViewModel() : base() { }
    	public TagMappingViewModel(DataService.Models.Entities.TagMapping entity) : base(entity) { }
    
    }
}
