//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Tag>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string TagName { get; set; }
    			public virtual string TagName_EN { get; set; }
    			public virtual Nullable<long> TagViews { get; set; }
    			public virtual Nullable<bool> TagActive { get; set; }
    			public virtual string Type { get; set; }
    	
    	public TagViewModel() : base() { }
    	public TagViewModel(DataService.Models.Entities.Tag entity) : base(entity) { }
    
    }
}
