//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDetailMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.TemplateDetailMapping>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int PaySlipTemplateId { get; set; }
    			public virtual Nullable<int> PayrollDetailId { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public TemplateDetailMappingViewModel() : base() { }
    	public TemplateDetailMappingViewModel(DataService.Models.Entities.TemplateDetailMapping entity) : base(entity) { }
    
    }
}
