//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Theme>
    {
    	
    			public virtual int ThemeId { get; set; }
    			public virtual string ThemeName { get; set; }
    			public virtual string ThemeFolderUrl { get; set; }
    			public virtual string ThemeStyle { get; set; }
    			public virtual string ImageUrl { get; set; }
    			public virtual System.DateTime CreatedDate { get; set; }
    			public virtual string CreatedBy { get; set; }
    			public virtual Nullable<System.DateTime> LastModifiedDate { get; set; }
    			public virtual string LastModifiedBy { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual string Description { get; set; }
    	
    	public ThemeViewModel() : base() { }
    	public ThemeViewModel(DataService.Models.Entities.Theme entity) : base(entity) { }
    
    }
}
