//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenUserViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.TokenUser>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Username { get; set; }
    			public virtual string Token { get; set; }
    			public virtual Nullable<System.DateTime> CreateTime { get; set; }
    			public virtual Nullable<System.DateTime> EndTime { get; set; }
    	
    	public TokenUserViewModel() : base() { }
    	public TokenUserViewModel(DataService.Models.Entities.TokenUser entity) : base(entity) { }
    
    }
}
