//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess_CampaignViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.UserAccess_Campaign>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int UserAccessId { get; set; }
    			public virtual int CampaignId { get; set; }
    	
    	public UserAccess_CampaignViewModel() : base() { }
    	public UserAccess_CampaignViewModel(DataService.Models.Entities.UserAccess_Campaign entity) : base(entity) { }
    
    }
}
