//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.User>
    {
    	
    			public virtual System.Guid ApplicationId { get; set; }
    			public virtual System.Guid UserId { get; set; }
    			public virtual string UserName { get; set; }
    			public virtual bool IsAnonymous { get; set; }
    			public virtual System.DateTime LastActivityDate { get; set; }
    	
    	public UserViewModel() : base() { }
    	public UserViewModel(DataService.Models.Entities.User entity) : base(entity) { }
    
    }
}
