//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATOrderMappingViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.VATOrderMapping>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int RentID { get; set; }
    			public virtual int InvoiceID { get; set; }
    	
    	public VATOrderMappingViewModel() : base() { }
    	public VATOrderMappingViewModel(DataService.Models.Entities.VATOrderMapping entity) : base(entity) { }
    
    }
}
