//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCounterViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ViewCounter>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual int OnlineCount { get; set; }
    			public virtual int TodayCount { get; set; }
    			public virtual int ThisWeekCount { get; set; }
    			public virtual int ThisMonthCount { get; set; }
    			public virtual int TotalCount { get; set; }
    	
    	public ViewCounterViewModel() : base() { }
    	public ViewCounterViewModel(DataService.Models.Entities.ViewCounter entity) : base(entity) { }
    
    }
}
