//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Voucher>
    {
    	
    			public virtual int VoucherID { get; set; }
    			public virtual string VoucherCode { get; set; }
    			public virtual Nullable<int> PromotionDetailID { get; set; }
    			public virtual int PromotionID { get; set; }
    			public virtual int Quantity { get; set; }
    			public virtual int UsedQuantity { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<bool> IsGetted { get; set; }
    			public virtual Nullable<bool> isUsed { get; set; }
    			public virtual Nullable<int> MembershipCardId { get; set; }
    	
    	public VoucherViewModel() : base() { }
    	public VoucherViewModel(DataService.Models.Entities.Voucher entity) : base(entity) { }
    
    }
}
