//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebElementViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.WebElement>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<int> ParentId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string Detail { get; set; }
    			public virtual string ImageUrl { get; set; }
    			public virtual string Link { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    	
    	public WebElementViewModel() : base() { }
    	public WebElementViewModel(DataService.Models.Entities.WebElement entity) : base(entity) { }
    
    }
}
