//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebMenuViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.WebMenu>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string MenuText { get; set; }
    			public virtual string MenuText1 { get; set; }
    			public virtual string MenuText2 { get; set; }
    			public virtual string Type { get; set; }
    			public virtual string Link { get; set; }
    			public virtual string IconUrl { get; set; }
    			public virtual int DisplayOrder { get; set; }
    			public virtual Nullable<int> ParentMenuId { get; set; }
    			public virtual Nullable<int> MenuLevel { get; set; }
    			public virtual Nullable<int> StoreFilter { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual bool IsSystemMenu { get; set; }
    			public virtual int CategoryId { get; set; }
    	
    	public WebMenuViewModel() : base() { }
    	public WebMenuViewModel(DataService.Models.Entities.WebMenu entity) : base(entity) { }
    
    }
}
