//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPageViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.WebPage>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Title { get; set; }
    			public virtual string PageContent { get; set; }
    			public virtual string PageTitle { get; set; }
    			public virtual string MetaDescription { get; set; }
    			public virtual bool IsActive { get; set; }
    			public virtual Nullable<int> StoreId { get; set; }
    			public virtual string SeoName { get; set; }
    			public virtual string MetaKeyword { get; set; }
    	
    	public WebPageViewModel() : base() { }
    	public WebPageViewModel(DataService.Models.Entities.WebPage entity) : base(entity) { }
    
    }
}
