//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IAreaDeliveryService : DataService.BaseConnect.IBaseService<AreaDelivery, AreaDeliveryViewModel>
    {
    }
    
    public partial class AreaDeliveryService : DataService.BaseConnect.BaseService<AreaDelivery, AreaDeliveryViewModel>, IAreaDeliveryService
    {
         public AreaDeliveryService()
         {
         }
        public AreaDeliveryService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IAreaDeliveryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
