//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IArticleService : DataService.BaseConnect.IBaseService<Article, ArticleViewModel>
    {
    }
    
    public partial class ArticleService : DataService.BaseConnect.BaseService<Article, ArticleViewModel>, IArticleService
    {
         public ArticleService()
         {
         }
        public ArticleService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IArticleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
