//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IAspNetUserLoginService : DataService.BaseConnect.IBaseService<AspNetUserLogin, AspNetUserLoginViewModel>
    {
    }
    
    public partial class AspNetUserLoginService : DataService.BaseConnect.BaseService<AspNetUserLogin, AspNetUserLoginViewModel>, IAspNetUserLoginService
    {
         public AspNetUserLoginService()
         {
         }
        public AspNetUserLoginService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IAspNetUserLoginRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
