//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IAspNetRoleService : DataService.BaseConnect.IBaseService<AspNetRole, AspNetRoleViewModel>
    {
    }
    
    public partial class AspNetRoleService : DataService.BaseConnect.BaseService<AspNetRole, AspNetRoleViewModel>, IAspNetRoleService
    {
         public AspNetRoleService()
         {
         }
        public AspNetRoleService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IAspNetRoleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
