//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IAttendanceDateService : DataService.BaseConnect.IBaseService<AttendanceDate, AttendanceDateViewModel>
    {
    }
    
    public partial class AttendanceDateService : DataService.BaseConnect.BaseService<AttendanceDate, AttendanceDateViewModel>, IAttendanceDateService
    {
         public AttendanceDateService()
         {
         }
        public AttendanceDateService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IAttendanceDateRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
