//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IBlogPostCollectionItemMappingService : DataService.BaseConnect.IBaseService<BlogPostCollectionItemMapping, BlogPostCollectionItemMappingViewModel>
    {
    }
    
    public partial class BlogPostCollectionItemMappingService : DataService.BaseConnect.BaseService<BlogPostCollectionItemMapping, BlogPostCollectionItemMappingViewModel>, IBlogPostCollectionItemMappingService
    {
         public BlogPostCollectionItemMappingService()
         {
         }
        public BlogPostCollectionItemMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IBlogPostCollectionItemMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
