//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IBlogPostImageService : DataService.BaseConnect.IBaseService<BlogPostImage, BlogPostImageViewModel>
    {
    }
    
    public partial class BlogPostImageService : DataService.BaseConnect.BaseService<BlogPostImage, BlogPostImageViewModel>, IBlogPostImageService
    {
         public BlogPostImageService()
         {
         }
        public BlogPostImageService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IBlogPostImageRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
