//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IBlogPostService : DataService.BaseConnect.IBaseService<BlogPost, BlogPostViewModel>
    {
    }
    
    public partial class BlogPostService : DataService.BaseConnect.BaseService<BlogPost, BlogPostViewModel>, IBlogPostService
    {
         public BlogPostService()
         {
         }
        public BlogPostService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IBlogPostRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
