//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IBrandService : DataService.BaseConnect.IBaseService<Brand, BrandViewModel>
    {
    }
    
    public partial class BrandService : DataService.BaseConnect.BaseService<Brand, BrandViewModel>, IBrandService
    {
         public BrandService()
         {
         }
        public BrandService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IBrandRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
