//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICategoryExtraService : DataService.BaseConnect.IBaseService<CategoryExtra, CategoryExtraViewModel>
    {
    }
    
    public partial class CategoryExtraService : DataService.BaseConnect.BaseService<CategoryExtra, CategoryExtraViewModel>, ICategoryExtraService
    {
         public CategoryExtraService()
         {
         }
        public CategoryExtraService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICategoryExtraRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
