//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICategoryExtraMappingService : DataService.BaseConnect.IBaseService<CategoryExtraMapping, CategoryExtraMappingViewModel>
    {
    }
    
    public partial class CategoryExtraMappingService : DataService.BaseConnect.BaseService<CategoryExtraMapping, CategoryExtraMappingViewModel>, ICategoryExtraMappingService
    {
         public CategoryExtraMappingService()
         {
         }
        public CategoryExtraMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICategoryExtraMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
