//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICheckFingerService : DataService.BaseConnect.IBaseService<CheckFinger, CheckFingerViewModel>
    {
    }
    
    public partial class CheckFingerService : DataService.BaseConnect.BaseService<CheckFinger, CheckFingerViewModel>, ICheckFingerService
    {
         public CheckFingerService()
         {
         }
        public CheckFingerService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICheckFingerRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
