//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICostInventoryMappingService : DataService.BaseConnect.IBaseService<CostInventoryMapping, CostInventoryMappingViewModel>
    {
    }
    
    public partial class CostInventoryMappingService : DataService.BaseConnect.BaseService<CostInventoryMapping, CostInventoryMappingViewModel>, ICostInventoryMappingService
    {
         public CostInventoryMappingService()
         {
         }
        public CostInventoryMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICostInventoryMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
