//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICostService : DataService.BaseConnect.IBaseService<Cost, CostViewModel>
    {
    }
    
    public partial class CostService : DataService.BaseConnect.BaseService<Cost, CostViewModel>, ICostService
    {
         public CostService()
         {
         }
        public CostService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICostRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
