//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICouponService : DataService.BaseConnect.IBaseService<Coupon, CouponViewModel>
    {
    }
    
    public partial class CouponService : DataService.BaseConnect.BaseService<Coupon, CouponViewModel>, ICouponService
    {
         public CouponService()
         {
         }
        public CouponService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICouponRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
