//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICustomerFeedbackService : DataService.BaseConnect.IBaseService<CustomerFeedback, CustomerFeedbackViewModel>
    {
    }
    
    public partial class CustomerFeedbackService : DataService.BaseConnect.BaseService<CustomerFeedback, CustomerFeedbackViewModel>, ICustomerFeedbackService
    {
         public CustomerFeedbackService()
         {
         }
        public CustomerFeedbackService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICustomerFeedbackRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
