//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICustomerFilterService : DataService.BaseConnect.IBaseService<CustomerFilter, CustomerFilterViewModel>
    {
    }
    
    public partial class CustomerFilterService : DataService.BaseConnect.BaseService<CustomerFilter, CustomerFilterViewModel>, ICustomerFilterService
    {
         public CustomerFilterService()
         {
         }
        public CustomerFilterService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICustomerFilterRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
