//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ICustomerStoreReportMappingService : DataService.BaseConnect.IBaseService<CustomerStoreReportMapping, CustomerStoreReportMappingViewModel>
    {
    }
    
    public partial class CustomerStoreReportMappingService : DataService.BaseConnect.BaseService<CustomerStoreReportMapping, CustomerStoreReportMappingViewModel>, ICustomerStoreReportMappingService
    {
         public CustomerStoreReportMappingService()
         {
         }
        public CustomerStoreReportMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ICustomerStoreReportMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
