//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IDateProductService : DataService.BaseConnect.IBaseService<DateProduct, DateProductViewModel>
    {
    }
    
    public partial class DateProductService : DataService.BaseConnect.BaseService<DateProduct, DateProductViewModel>, IDateProductService
    {
         public DateProductService()
         {
         }
        public DateProductService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IDateProductRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
