//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IDayModeService : DataService.BaseConnect.IBaseService<DayMode, DayModeViewModel>
    {
    }
    
    public partial class DayModeService : DataService.BaseConnect.BaseService<DayMode, DayModeViewModel>, IDayModeService
    {
         public DayModeService()
         {
         }
        public DayModeService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IDayModeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
