//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IDeliveryInformationService : DataService.BaseConnect.IBaseService<DeliveryInformation, DeliveryInformationViewModel>
    {
    }
    
    public partial class DeliveryInformationService : DataService.BaseConnect.BaseService<DeliveryInformation, DeliveryInformationViewModel>, IDeliveryInformationService
    {
         public DeliveryInformationService()
         {
         }
        public DeliveryInformationService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IDeliveryInformationRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
