//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IDeviceService : DataService.BaseConnect.IBaseService<Device, DeviceViewModel>
    {
    }
    
    public partial class DeviceService : DataService.BaseConnect.BaseService<Device, DeviceViewModel>, IDeviceService
    {
         public DeviceService()
         {
         }
        public DeviceService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IDeviceRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
