//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IEmployeeFingerService : DataService.BaseConnect.IBaseService<EmployeeFinger, EmployeeFingerViewModel>
    {
    }
    
    public partial class EmployeeFingerService : DataService.BaseConnect.BaseService<EmployeeFinger, EmployeeFingerViewModel>, IEmployeeFingerService
    {
         public EmployeeFingerService()
         {
         }
        public EmployeeFingerService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IEmployeeFingerRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
