//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IEmployeeService : DataService.BaseConnect.IBaseService<Employee, EmployeeViewModel>
    {
    }
    
    public partial class EmployeeService : DataService.BaseConnect.BaseService<Employee, EmployeeViewModel>, IEmployeeService
    {
         public EmployeeService()
         {
         }
        public EmployeeService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IEmployeeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
