//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IEmployeeAttributeService : DataService.BaseConnect.IBaseService<EmployeeAttribute, EmployeeAttributeViewModel>
    {
    }
    
    public partial class EmployeeAttributeService : DataService.BaseConnect.BaseService<EmployeeAttribute, EmployeeAttributeViewModel>, IEmployeeAttributeService
    {
         public EmployeeAttributeService()
         {
         }
        public EmployeeAttributeService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IEmployeeAttributeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
