//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IEmployeeGroupService : DataService.BaseConnect.IBaseService<EmployeeGroup, EmployeeGroupViewModel>
    {
    }
    
    public partial class EmployeeGroupService : DataService.BaseConnect.BaseService<EmployeeGroup, EmployeeGroupViewModel>, IEmployeeGroupService
    {
         public EmployeeGroupService()
         {
         }
        public EmployeeGroupService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IEmployeeGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
