//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IEventLocationService : DataService.BaseConnect.IBaseService<EventLocation, EventLocationViewModel>
    {
    }
    
    public partial class EventLocationService : DataService.BaseConnect.BaseService<EventLocation, EventLocationViewModel>, IEventLocationService
    {
         public EventLocationService()
         {
         }
        public EventLocationService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IEventLocationRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
