//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IImageCollectionService : DataService.BaseConnect.IBaseService<ImageCollection, ImageCollectionViewModel>
    {
    }
    
    public partial class ImageCollectionService : DataService.BaseConnect.BaseService<ImageCollection, ImageCollectionViewModel>, IImageCollectionService
    {
         public ImageCollectionService()
         {
         }
        public ImageCollectionService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IImageCollectionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
