//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IImageCollectionItemService : DataService.BaseConnect.IBaseService<ImageCollectionItem, ImageCollectionItemViewModel>
    {
    }
    
    public partial class ImageCollectionItemService : DataService.BaseConnect.BaseService<ImageCollectionItem, ImageCollectionItemViewModel>, IImageCollectionItemService
    {
         public ImageCollectionItemService()
         {
         }
        public ImageCollectionItemService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IImageCollectionItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
