//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IInventoryReceiptService : DataService.BaseConnect.IBaseService<InventoryReceipt, InventoryReceiptViewModel>
    {
    }
    
    public partial class InventoryReceiptService : DataService.BaseConnect.BaseService<InventoryReceipt, InventoryReceiptViewModel>, IInventoryReceiptService
    {
         public InventoryReceiptService()
         {
         }
        public InventoryReceiptService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IInventoryReceiptRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
