//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IInventoryDateReportService : DataService.BaseConnect.IBaseService<InventoryDateReport, InventoryDateReportViewModel>
    {
    }
    
    public partial class InventoryDateReportService : DataService.BaseConnect.BaseService<InventoryDateReport, InventoryDateReportViewModel>, IInventoryDateReportService
    {
         public InventoryDateReportService()
         {
         }
        public InventoryDateReportService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IInventoryDateReportRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
