//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IInventoryReceiptItemService : DataService.BaseConnect.IBaseService<InventoryReceiptItem, InventoryReceiptItemViewModel>
    {
    }
    
    public partial class InventoryReceiptItemService : DataService.BaseConnect.BaseService<InventoryReceiptItem, InventoryReceiptItemViewModel>, IInventoryReceiptItemService
    {
         public InventoryReceiptItemService()
         {
         }
        public InventoryReceiptItemService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IInventoryReceiptItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
