//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IInventoryCheckingItemService : DataService.BaseConnect.IBaseService<InventoryCheckingItem, InventoryCheckingItemViewModel>
    {
    }
    
    public partial class InventoryCheckingItemService : DataService.BaseConnect.BaseService<InventoryCheckingItem, InventoryCheckingItemViewModel>, IInventoryCheckingItemService
    {
         public InventoryCheckingItemService()
         {
         }
        public InventoryCheckingItemService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IInventoryCheckingItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
