//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ILanguageKeyService : DataService.BaseConnect.IBaseService<LanguageKey, LanguageKeyViewModel>
    {
    }
    
    public partial class LanguageKeyService : DataService.BaseConnect.BaseService<LanguageKey, LanguageKeyViewModel>, ILanguageKeyService
    {
         public LanguageKeyService()
         {
         }
        public LanguageKeyService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ILanguageKeyRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
