//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IMembershipTypeService : DataService.BaseConnect.IBaseService<MembershipType, MembershipTypeViewModel>
    {
    }
    
    public partial class MembershipTypeService : DataService.BaseConnect.BaseService<MembershipType, MembershipTypeViewModel>, IMembershipTypeService
    {
         public MembershipTypeService()
         {
         }
        public MembershipTypeService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IMembershipTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
