//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IMenuService : DataService.BaseConnect.IBaseService<Menu, MenuViewModel>
    {
    }
    
    public partial class MenuService : DataService.BaseConnect.BaseService<Menu, MenuViewModel>, IMenuService
    {
         public MenuService()
         {
         }
        public MenuService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IMenuRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
