//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface INotificationService : DataService.BaseConnect.IBaseService<Notification, NotificationViewModel>
    {
    }
    
    public partial class NotificationService : DataService.BaseConnect.BaseService<Notification, NotificationViewModel>, INotificationService
    {
         public NotificationService()
         {
         }
        public NotificationService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.INotificationRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
