//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IOrderDetailService : DataService.BaseConnect.IBaseService<OrderDetail, OrderDetailViewModel>
    {
    }
    
    public partial class OrderDetailService : DataService.BaseConnect.BaseService<OrderDetail, OrderDetailViewModel>, IOrderDetailService
    {
         public OrderDetailService()
         {
         }
        public OrderDetailService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IOrderDetailRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
