//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IOrderDetailPromotionMappingService : DataService.BaseConnect.IBaseService<OrderDetailPromotionMapping, OrderDetailPromotionMappingViewModel>
    {
    }
    
    public partial class OrderDetailPromotionMappingService : DataService.BaseConnect.BaseService<OrderDetailPromotionMapping, OrderDetailPromotionMappingViewModel>, IOrderDetailPromotionMappingService
    {
         public OrderDetailPromotionMappingService()
         {
         }
        public OrderDetailPromotionMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IOrderDetailPromotionMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
