//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IOrderPromotionMappingService : DataService.BaseConnect.IBaseService<OrderPromotionMapping, OrderPromotionMappingViewModel>
    {
    }
    
    public partial class OrderPromotionMappingService : DataService.BaseConnect.BaseService<OrderPromotionMapping, OrderPromotionMappingViewModel>, IOrderPromotionMappingService
    {
         public OrderPromotionMappingService()
         {
         }
        public OrderPromotionMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IOrderPromotionMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
