//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IOrderService : DataService.BaseConnect.IBaseService<Order, OrderViewModel>
    {
    }
    
    public partial class OrderService : DataService.BaseConnect.BaseService<Order, OrderViewModel>, IOrderService
    {
         public OrderService()
         {
         }
        public OrderService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IOrderRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
