//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPartnerMappingService : DataService.BaseConnect.IBaseService<PartnerMapping, PartnerMappingViewModel>
    {
    }
    
    public partial class PartnerMappingService : DataService.BaseConnect.BaseService<PartnerMapping, PartnerMappingViewModel>, IPartnerMappingService
    {
         public PartnerMappingService()
         {
         }
        public PartnerMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPartnerMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
