//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPaymentService : DataService.BaseConnect.IBaseService<Payment, PaymentViewModel>
    {
    }
    
    public partial class PaymentService : DataService.BaseConnect.BaseService<Payment, PaymentViewModel>, IPaymentService
    {
         public PaymentService()
         {
         }
        public PaymentService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPaymentRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
