//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPaymentReportService : DataService.BaseConnect.IBaseService<PaymentReport, PaymentReportViewModel>
    {
    }
    
    public partial class PaymentReportService : DataService.BaseConnect.BaseService<PaymentReport, PaymentReportViewModel>, IPaymentReportService
    {
         public PaymentReportService()
         {
         }
        public PaymentReportService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPaymentReportRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
