//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPayrollCategoryService : DataService.BaseConnect.IBaseService<PayrollCategory, PayrollCategoryViewModel>
    {
    }
    
    public partial class PayrollCategoryService : DataService.BaseConnect.BaseService<PayrollCategory, PayrollCategoryViewModel>, IPayrollCategoryService
    {
         public PayrollCategoryService()
         {
         }
        public PayrollCategoryService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPayrollCategoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
