//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPayrollPeriodService : DataService.BaseConnect.IBaseService<PayrollPeriod, PayrollPeriodViewModel>
    {
    }
    
    public partial class PayrollPeriodService : DataService.BaseConnect.BaseService<PayrollPeriod, PayrollPeriodViewModel>, IPayrollPeriodService
    {
         public PayrollPeriodService()
         {
         }
        public PayrollPeriodService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPayrollPeriodRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
