//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPayslipAttributeMappingService : DataService.BaseConnect.IBaseService<PayslipAttributeMapping, PayslipAttributeMappingViewModel>
    {
    }
    
    public partial class PayslipAttributeMappingService : DataService.BaseConnect.BaseService<PayslipAttributeMapping, PayslipAttributeMappingViewModel>, IPayslipAttributeMappingService
    {
         public PayslipAttributeMappingService()
         {
         }
        public PayslipAttributeMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPayslipAttributeMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
