//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPaySlipService : DataService.BaseConnect.IBaseService<PaySlip, PaySlipViewModel>
    {
    }
    
    public partial class PaySlipService : DataService.BaseConnect.BaseService<PaySlip, PaySlipViewModel>, IPaySlipService
    {
         public PaySlipService()
         {
         }
        public PaySlipService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPaySlipRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
