//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPriceNightService : DataService.BaseConnect.IBaseService<PriceNight, PriceNightViewModel>
    {
    }
    
    public partial class PriceNightService : DataService.BaseConnect.BaseService<PriceNight, PriceNightViewModel>, IPriceNightService
    {
         public PriceNightService()
         {
         }
        public PriceNightService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPriceNightRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
