//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPriceAdditionService : DataService.BaseConnect.IBaseService<PriceAddition, PriceAdditionViewModel>
    {
    }
    
    public partial class PriceAdditionService : DataService.BaseConnect.BaseService<PriceAddition, PriceAdditionViewModel>, IPriceAdditionService
    {
         public PriceAdditionService()
         {
         }
        public PriceAdditionService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPriceAdditionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
