//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProductImageService : DataService.BaseConnect.IBaseService<ProductImage, ProductImageViewModel>
    {
    }
    
    public partial class ProductImageService : DataService.BaseConnect.BaseService<ProductImage, ProductImageViewModel>, IProductImageService
    {
         public ProductImageService()
         {
         }
        public ProductImageService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProductImageRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
