//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProductImageCollectionService : DataService.BaseConnect.IBaseService<ProductImageCollection, ProductImageCollectionViewModel>
    {
    }
    
    public partial class ProductImageCollectionService : DataService.BaseConnect.BaseService<ProductImageCollection, ProductImageCollectionViewModel>, IProductImageCollectionService
    {
         public ProductImageCollectionService()
         {
         }
        public ProductImageCollectionService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProductImageCollectionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
