//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProductService : DataService.BaseConnect.IBaseService<Product, ProductViewModel>
    {
    }
    
    public partial class ProductService : DataService.BaseConnect.BaseService<Product, ProductViewModel>, IProductService
    {
         public ProductService()
         {
         }
        public ProductService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProductRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
