//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProductItemCompositionMappingService : DataService.BaseConnect.IBaseService<ProductItemCompositionMapping, ProductItemCompositionMappingViewModel>
    {
    }
    
    public partial class ProductItemCompositionMappingService : DataService.BaseConnect.BaseService<ProductItemCompositionMapping, ProductItemCompositionMappingViewModel>, IProductItemCompositionMappingService
    {
         public ProductItemCompositionMappingService()
         {
         }
        public ProductItemCompositionMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProductItemCompositionMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
