//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProductItemService : DataService.BaseConnect.IBaseService<ProductItem, ProductItemViewModel>
    {
    }
    
    public partial class ProductItemService : DataService.BaseConnect.BaseService<ProductItem, ProductItemViewModel>, IProductItemService
    {
         public ProductItemService()
         {
         }
        public ProductItemService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProductItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
