//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProductDetailMappingService : DataService.BaseConnect.IBaseService<ProductDetailMapping, ProductDetailMappingViewModel>
    {
    }
    
    public partial class ProductDetailMappingService : DataService.BaseConnect.BaseService<ProductDetailMapping, ProductDetailMappingViewModel>, IProductDetailMappingService
    {
         public ProductDetailMappingService()
         {
         }
        public ProductDetailMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProductDetailMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
