//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProductComboDetailService : DataService.BaseConnect.IBaseService<ProductComboDetail, ProductComboDetailViewModel>
    {
    }
    
    public partial class ProductComboDetailService : DataService.BaseConnect.BaseService<ProductComboDetail, ProductComboDetailViewModel>, IProductComboDetailService
    {
         public ProductComboDetailService()
         {
         }
        public ProductComboDetailService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProductComboDetailRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
