//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProductCategoryService : DataService.BaseConnect.IBaseService<ProductCategory, ProductCategoryViewModel>
    {
    }
    
    public partial class ProductCategoryService : DataService.BaseConnect.BaseService<ProductCategory, ProductCategoryViewModel>, IProductCategoryService
    {
         public ProductCategoryService()
         {
         }
        public ProductCategoryService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProductCategoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
