//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProfileService : DataService.BaseConnect.IBaseService<Profile, ProfileViewModel>
    {
    }
    
    public partial class ProfileService : DataService.BaseConnect.BaseService<Profile, ProfileViewModel>, IProfileService
    {
         public ProfileService()
         {
         }
        public ProfileService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProfileRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
