//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPromotionService : DataService.BaseConnect.IBaseService<Promotion, PromotionViewModel>
    {
    }
    
    public partial class PromotionService : DataService.BaseConnect.BaseService<Promotion, PromotionViewModel>, IPromotionService
    {
         public PromotionService()
         {
         }
        public PromotionService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPromotionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
