//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IPromotionDetailService : DataService.BaseConnect.IBaseService<PromotionDetail, PromotionDetailViewModel>
    {
    }
    
    public partial class PromotionDetailService : DataService.BaseConnect.BaseService<PromotionDetail, PromotionDetailViewModel>, IPromotionDetailService
    {
         public PromotionDetailService()
         {
         }
        public PromotionDetailService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IPromotionDetailRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
