//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProviderService : DataService.BaseConnect.IBaseService<Provider, ProviderViewModel>
    {
    }
    
    public partial class ProviderService : DataService.BaseConnect.BaseService<Provider, ProviderViewModel>, IProviderService
    {
         public ProviderService()
         {
         }
        public ProviderService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProviderRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
