//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProvinceService : DataService.BaseConnect.IBaseService<Province, ProvinceViewModel>
    {
    }
    
    public partial class ProvinceService : DataService.BaseConnect.BaseService<Province, ProvinceViewModel>, IProvinceService
    {
         public ProvinceService()
         {
         }
        public ProvinceService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProvinceRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
