//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProviderProductItemMappingService : DataService.BaseConnect.IBaseService<ProviderProductItemMapping, ProviderProductItemMappingViewModel>
    {
    }
    
    public partial class ProviderProductItemMappingService : DataService.BaseConnect.BaseService<ProviderProductItemMapping, ProviderProductItemMappingViewModel>, IProviderProductItemMappingService
    {
         public ProviderProductItemMappingService()
         {
         }
        public ProviderProductItemMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProviderProductItemMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
