//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IRatingStarService : DataService.BaseConnect.IBaseService<RatingStar, RatingStarViewModel>
    {
    }
    
    public partial class RatingStarService : DataService.BaseConnect.BaseService<RatingStar, RatingStarViewModel>, IRatingStarService
    {
         public RatingStarService()
         {
         }
        public RatingStarService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IRatingStarRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
