//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IRatingService : DataService.BaseConnect.IBaseService<Rating, RatingViewModel>
    {
    }
    
    public partial class RatingService : DataService.BaseConnect.BaseService<Rating, RatingViewModel>, IRatingService
    {
         public RatingService()
         {
         }
        public RatingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IRatingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
