//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IReportTrackingService : DataService.BaseConnect.IBaseService<ReportTracking, ReportTrackingViewModel>
    {
    }
    
    public partial class ReportTrackingService : DataService.BaseConnect.BaseService<ReportTracking, ReportTrackingViewModel>, IReportTrackingService
    {
         public ReportTrackingService()
         {
         }
        public ReportTrackingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IReportTrackingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
