//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IRoleService : DataService.BaseConnect.IBaseService<Role, RoleViewModel>
    {
    }
    
    public partial class RoleService : DataService.BaseConnect.BaseService<Role, RoleViewModel>, IRoleService
    {
         public RoleService()
         {
         }
        public RoleService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IRoleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
