//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IRoomCategoryService : DataService.BaseConnect.IBaseService<RoomCategory, RoomCategoryViewModel>
    {
    }
    
    public partial class RoomCategoryService : DataService.BaseConnect.BaseService<RoomCategory, RoomCategoryViewModel>, IRoomCategoryService
    {
         public RoomCategoryService()
         {
         }
        public RoomCategoryService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IRoomCategoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
