//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IRoomCategoryPriceGroupMappingService : DataService.BaseConnect.IBaseService<RoomCategoryPriceGroupMapping, RoomCategoryPriceGroupMappingViewModel>
    {
    }
    
    public partial class RoomCategoryPriceGroupMappingService : DataService.BaseConnect.BaseService<RoomCategoryPriceGroupMapping, RoomCategoryPriceGroupMappingViewModel>, IRoomCategoryPriceGroupMappingService
    {
         public RoomCategoryPriceGroupMappingService()
         {
         }
        public RoomCategoryPriceGroupMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IRoomCategoryPriceGroupMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
