//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ISalaryHourService : DataService.BaseConnect.IBaseService<SalaryHour, SalaryHourViewModel>
    {
    }
    
    public partial class SalaryHourService : DataService.BaseConnect.BaseService<SalaryHour, SalaryHourViewModel>, ISalaryHourService
    {
         public SalaryHourService()
         {
         }
        public SalaryHourService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ISalaryHourRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
