//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ISalaryRuleService : DataService.BaseConnect.IBaseService<SalaryRule, SalaryRuleViewModel>
    {
    }
    
    public partial class SalaryRuleService : DataService.BaseConnect.BaseService<SalaryRule, SalaryRuleViewModel>, ISalaryRuleService
    {
         public SalaryRuleService()
         {
         }
        public SalaryRuleService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ISalaryRuleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
