//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IStoreUserService : DataService.BaseConnect.IBaseService<StoreUser, StoreUserViewModel>
    {
    }
    
    public partial class StoreUserService : DataService.BaseConnect.BaseService<StoreUser, StoreUserViewModel>, IStoreUserService
    {
         public StoreUserService()
         {
         }
        public StoreUserService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IStoreUserRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
