//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IStoreGroupService : DataService.BaseConnect.IBaseService<StoreGroup, StoreGroupViewModel>
    {
    }
    
    public partial class StoreGroupService : DataService.BaseConnect.BaseService<StoreGroup, StoreGroupViewModel>, IStoreGroupService
    {
         public StoreGroupService()
         {
         }
        public StoreGroupService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IStoreGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
