//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IStoreService : DataService.BaseConnect.IBaseService<Store, StoreViewModel>
    {
    }
    
    public partial class StoreService : DataService.BaseConnect.BaseService<Store, StoreViewModel>, IStoreService
    {
         public StoreService()
         {
         }
        public StoreService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IStoreRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
