//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IStoreWebRouteModelService : DataService.BaseConnect.IBaseService<StoreWebRouteModel, StoreWebRouteModelViewModel>
    {
    }
    
    public partial class StoreWebRouteModelService : DataService.BaseConnect.BaseService<StoreWebRouteModel, StoreWebRouteModelViewModel>, IStoreWebRouteModelService
    {
         public StoreWebRouteModelService()
         {
         }
        public StoreWebRouteModelService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IStoreWebRouteModelRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
