//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IStoreThemeService : DataService.BaseConnect.IBaseService<StoreTheme, StoreThemeViewModel>
    {
    }
    
    public partial class StoreThemeService : DataService.BaseConnect.BaseService<StoreTheme, StoreThemeViewModel>, IStoreThemeService
    {
         public StoreThemeService()
         {
         }
        public StoreThemeService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IStoreThemeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
