//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ISubRentGroupService : DataService.BaseConnect.IBaseService<SubRentGroup, SubRentGroupViewModel>
    {
    }
    
    public partial class SubRentGroupService : DataService.BaseConnect.BaseService<SubRentGroup, SubRentGroupViewModel>, ISubRentGroupService
    {
         public SubRentGroupService()
         {
         }
        public SubRentGroupService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ISubRentGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
