//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ISystemPartnerMappingService : DataService.BaseConnect.IBaseService<SystemPartnerMapping, SystemPartnerMappingViewModel>
    {
    }
    
    public partial class SystemPartnerMappingService : DataService.BaseConnect.BaseService<SystemPartnerMapping, SystemPartnerMappingViewModel>, ISystemPartnerMappingService
    {
         public SystemPartnerMappingService()
         {
         }
        public SystemPartnerMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ISystemPartnerMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
