//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITagMappingService : DataService.BaseConnect.IBaseService<TagMapping, TagMappingViewModel>
    {
    }
    
    public partial class TagMappingService : DataService.BaseConnect.BaseService<TagMapping, TagMappingViewModel>, ITagMappingService
    {
         public TagMappingService()
         {
         }
        public TagMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITagMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
