//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITagService : DataService.BaseConnect.IBaseService<Tag, TagViewModel>
    {
    }
    
    public partial class TagService : DataService.BaseConnect.BaseService<Tag, TagViewModel>, ITagService
    {
         public TagService()
         {
         }
        public TagService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITagRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
