//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITaskDetailService : DataService.BaseConnect.IBaseService<TaskDetail, TaskDetailViewModel>
    {
    }
    
    public partial class TaskDetailService : DataService.BaseConnect.BaseService<TaskDetail, TaskDetailViewModel>, ITaskDetailService
    {
         public TaskDetailService()
         {
         }
        public TaskDetailService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITaskDetailRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
