//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITemplateReportProductItemMappingService : DataService.BaseConnect.IBaseService<TemplateReportProductItemMapping, TemplateReportProductItemMappingViewModel>
    {
    }
    
    public partial class TemplateReportProductItemMappingService : DataService.BaseConnect.BaseService<TemplateReportProductItemMapping, TemplateReportProductItemMappingViewModel>, ITemplateReportProductItemMappingService
    {
         public TemplateReportProductItemMappingService()
         {
         }
        public TemplateReportProductItemMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITemplateReportProductItemMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
