//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITemplateRuleMappingService : DataService.BaseConnect.IBaseService<TemplateRuleMapping, TemplateRuleMappingViewModel>
    {
    }
    
    public partial class TemplateRuleMappingService : DataService.BaseConnect.BaseService<TemplateRuleMapping, TemplateRuleMappingViewModel>, ITemplateRuleMappingService
    {
         public TemplateRuleMappingService()
         {
         }
        public TemplateRuleMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITemplateRuleMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
