//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITemplateDetailMappingService : DataService.BaseConnect.IBaseService<TemplateDetailMapping, TemplateDetailMappingViewModel>
    {
    }
    
    public partial class TemplateDetailMappingService : DataService.BaseConnect.BaseService<TemplateDetailMapping, TemplateDetailMappingViewModel>, ITemplateDetailMappingService
    {
         public TemplateDetailMappingService()
         {
         }
        public TemplateDetailMappingService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITemplateDetailMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
