//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITimeFrameService : DataService.BaseConnect.IBaseService<TimeFrame, TimeFrameViewModel>
    {
    }
    
    public partial class TimeFrameService : DataService.BaseConnect.BaseService<TimeFrame, TimeFrameViewModel>, ITimeFrameService
    {
         public TimeFrameService()
         {
         }
        public TimeFrameService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITimeFrameRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
