//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITokenUserService : DataService.BaseConnect.IBaseService<TokenUser, TokenUserViewModel>
    {
    }
    
    public partial class TokenUserService : DataService.BaseConnect.BaseService<TokenUser, TokenUserViewModel>, ITokenUserService
    {
         public TokenUserService()
         {
         }
        public TokenUserService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITokenUserRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
