//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITransactionService : DataService.BaseConnect.IBaseService<Transaction, TransactionViewModel>
    {
    }
    
    public partial class TransactionService : DataService.BaseConnect.BaseService<Transaction, TransactionViewModel>, ITransactionService
    {
         public TransactionService()
         {
         }
        public TransactionService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITransactionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
