//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IUserAccessService : DataService.BaseConnect.IBaseService<UserAccess, UserAccessViewModel>
    {
    }
    
    public partial class UserAccessService : DataService.BaseConnect.BaseService<UserAccess, UserAccessViewModel>, IUserAccessService
    {
         public UserAccessService()
         {
         }
        public UserAccessService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IUserAccessRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
