//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IViewCounterService : DataService.BaseConnect.IBaseService<ViewCounter, ViewCounterViewModel>
    {
    }
    
    public partial class ViewCounterService : DataService.BaseConnect.BaseService<ViewCounter, ViewCounterViewModel>, IViewCounterService
    {
         public ViewCounterService()
         {
         }
        public ViewCounterService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IViewCounterRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
