//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IVoucherService : DataService.BaseConnect.IBaseService<Voucher, VoucherViewModel>
    {
    }
    
    public partial class VoucherService : DataService.BaseConnect.BaseService<Voucher, VoucherViewModel>, IVoucherService
    {
         public VoucherService()
         {
         }
        public VoucherService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IVoucherRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
