//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IWardService : DataService.BaseConnect.IBaseService<Ward, WardViewModel>
    {
    }
    
    public partial class WardService : DataService.BaseConnect.BaseService<Ward, WardViewModel>, IWardService
    {
         public WardService()
         {
         }
        public WardService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IWardRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
