//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IWebCustomerFeedbackService : DataService.BaseConnect.IBaseService<WebCustomerFeedback, WebCustomerFeedbackViewModel>
    {
    }
    
    public partial class WebCustomerFeedbackService : DataService.BaseConnect.BaseService<WebCustomerFeedback, WebCustomerFeedbackViewModel>, IWebCustomerFeedbackService
    {
         public WebCustomerFeedbackService()
         {
         }
        public WebCustomerFeedbackService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IWebCustomerFeedbackRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
