//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IWebElementService : DataService.BaseConnect.IBaseService<WebElement, WebElementViewModel>
    {
    }
    
    public partial class WebElementService : DataService.BaseConnect.BaseService<WebElement, WebElementViewModel>, IWebElementService
    {
         public WebElementService()
         {
         }
        public WebElementService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IWebElementRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
