//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IWebMenuService : DataService.BaseConnect.IBaseService<WebMenu, WebMenuViewModel>
    {
    }
    
    public partial class WebMenuService : DataService.BaseConnect.BaseService<WebMenu, WebMenuViewModel>, IWebMenuService
    {
         public WebMenuService()
         {
         }
        public WebMenuService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IWebMenuRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
