//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IWebPageService : DataService.BaseConnect.IBaseService<WebPage, WebPageViewModel>
    {
    }
    
    public partial class WebPageService : DataService.BaseConnect.BaseService<WebPage, WebPageViewModel>, IWebPageService
    {
         public WebPageService()
         {
         }
        public WebPageService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IWebPageRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
