//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public int IdCardType { get; set; }
        public string CardCode { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int BrandId { get; set; }
        public int MembershipId { get; set; }
        public bool Active { get; set; }
        public string CreateBy { get; set; }
        public Nullable<bool> IsSample { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Membership Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
