//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membership()
        {
            this.Accounts = new HashSet<Account>();
            this.Cards = new HashSet<Card>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CSV { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> C_Level { get; set; }
        public Nullable<int> MembershipTypeId { get; set; }
        public Nullable<bool> IsSample { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<double> InitialValue { get; set; }
        public string MembershipCode { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> BrandId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual MembershipType MembershipType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
