//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> Star { get; set; }
        public string ReviewContent { get; set; }
        public bool Active { get; set; }
        public string ReviewEmail { get; set; }
        public string ReviewName { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<int> Rate1 { get; set; }
        public Nullable<int> Rate2 { get; set; }
        public Nullable<int> Rate3 { get; set; }
        public Nullable<int> Rate4 { get; set; }
        public Nullable<int> Rate5 { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
