//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistory
    {
        public int ID { get; set; }
        public int StoreId { get; set; }
        public int BrandId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public string RequestData { get; set; }
        public string RequestToken { get; set; }
        public string RequestType { get; set; }
        public string RequestUri { get; set; }
        public string ControllerName { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<bool> Success { get; set; }
        public string Message { get; set; }
        public string ResponseData { get; set; }
    }
}
