//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int RoomID { get; set; }
        public string RoomName { get; set; }
        public string RoomDescription { get; set; }
        public int RoomStatus { get; set; }
        public int FloorID { get; set; }
        public int CategoryID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CurrentRentId { get; set; }
        public Nullable<int> RentStatus { get; set; }
        public int PosX { get; set; }
        public int PosSpanX { get; set; }
        public int PosY { get; set; }
        public int PosSpanY { get; set; }
        public Nullable<int> RentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual RoomCategory RoomCategory { get; set; }
        public virtual RoomFloor RoomFloor { get; set; }
    }
}
